apiVersion: v1
kind: Service
metadata:
  name: hello-docker-service
spec:
  selector:
    app: hello-docker
  ports:
  - protocol: "TCP"
    port: 5002
    targetPort: 5000
  type: LoadBalancer


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-docker
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: hello-docker
    spec:
      containers:
      - name: hello-docker
        image: hello-docker:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000